# Forward real internet requests to Google DNS
server=8.8.8.8
server=8.8.4.4

# LOCAL PROJECT SITES (add address=/"site"/127.0.0.1 when user registers and restart dns container)
address=/example.now/127.0.0.1
address=/milanovohosting.gg/127.0.0.1
address=/www.404error.com/127.0.0.1
address=/www.blackfridaysales.com/127.0.0.1
address=/www.monitor.com/127.0.0.1
address=/www.mrcamel.com/127.0.0.1
address=/www.randomizer.com/127.0.0.1