FROM gists/pure-ftpd:1.0.53

COPY entrypoint_ftp.sh /entrypoint_ftp.sh
COPY create_ftp_user.sh /create_ftp_user.sh
COPY delete_file.sh /delete_file.sh
COPY upload_file.sh /upload_file.sh

RUN sed -i 's/\r$//' /entrypoint_ftp.sh \
    && sed -i 's/\r$//' /create_ftp_user.sh \
    && sed -i 's/\r$//' /delete_file.sh \
    && sed -i 's/\r$//' /upload_file.sh \
    && chmod +x /entrypoint_ftp.sh /create_ftp_user.sh /delete_file.sh /upload_file.sh

ENTRYPOINT ["/entrypoint_ftp.sh"]